# Generated by Django 6.0.6 on 2026-07-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
