from django.urls import path
from . import views

urlpatterns = [

    path(
        'dashboard/',
        views.dashboard,
        name='receptionist_dashboard'
    ),

    path(
        'requests/',
        views.appointment_requests,
        name='appointment_requests'
    ),

    path(
        'patients/',
        views.patients,
        name='patients'
    ),

    path(
        'appointments/',
        views.appointments,
        name='appointments'
    ),
    path(
    "appointment-requests/<int:request_id>/",
    views.request_detail,
    name="request_detail",
    ),
    path(
    "approve-request/<int:request_id>/",
    views.approve_request,
    name="approve_request",
    ),
    path(
    "reject-request/<int:request_id>/",
    views.reject_request,
    name="reject_request",
    ),
    path(
    "patients/<int:patient_id>/",
    views.patient_detail,
    name="patient_detail",
    ),
    path(
    "patients/edit/<int:patient_id>/",
    views.edit_patient,
    name="edit_patient",
    ),
    path(
    "appointments/start/<int:appointment_id>/",
    views.start_consultation,
    name="start_consultation"
    ),

    path(
    "prescriptions/",
    views.prescriptions,
    name="receptionist_prescriptions"
    ),
    path(
    "prescriptions/given/<int:prescription_id>/",
    views.mark_medicine_given,
    name="mark_medicine_given"
    ),
    path(
    "settings/",
    views.settings,
    name="receptionist_settings"
    ),
    path(
    "profile/",
    views.profile,
    name="receptionist_profile"
    ),
    path(
    "profile/edit/",
    views.edit_profile,
    name="edit_profile"
    ),
    path(
    "change-password/",
    views.change_password,
    name="change_password"
    ),
    path(
    "appointments/cancel/<int:appointment_id>/",
    views.cancel_appointment,
    name="cancel_appointment"
    ),
    path(
    "patients/add/",
    views.add_patient,
    name="add_patient"
    ),
]