# Generated by Django 6.0.6 on 2026-08-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('patient', 'Patient')], max_length=20),
        ),
    ]
