# Generated by Django 6.0.6 on 2026-07-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
