# Generated by Django 6.0.6 on 2026-07-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescription_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicine_given',
            field=models.BooleanField(default=False),
        ),
    ]
