# Generated by Django 6.0.6 on 2026-07-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_prescription_medicine_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
