# Generated by Django 6.0.6 on 2026-07-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_prescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='billing_done',
            field=models.BooleanField(default=False),
        ),
    ]
