# Generated by Django 6.0.7 on 2026-08-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
