# Generated by Django 6.0.6 on 2026-07-27 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0002_alter_patient_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True)),
                ('past_diseases', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=30)),
                ('weight', models.CharField(blank=True, max_length=20)),
                ('current_problem', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
