# Generated by Django 6.0.6 on 2026-07-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_prescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
