# Generated by Django 6.0.6 on 2026-07-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctorsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsettings',
            name='dark_mode',
        ),
    ]
