# Generated by Django 6.0.6 on 2026-07-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_remove_doctorsettings_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsettings',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='max_patients_per_day',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
