# Generated by Django 6.0.6 on 2026-07-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctorsettings_dark_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsettings',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='google_map_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
