# Generated by Django 6.0.6 on 2026-07-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctorsettings_address_doctorsettings_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='aggravation_factors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='ambition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='amelioration_factors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='anger_reaction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='appetite_scale',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='concomitants',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='consolation_reaction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='criticism_response',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='diet_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='dream_themes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='etiology',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='etiology_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='family_miasms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='fears',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='food_aversions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='food_cravings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='food_intolerances',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='future_outlook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='location_extension',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='meal_pattern',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='memory_concentration',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='orderliness',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='pace_of_actions',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='physical_build',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='self_perception',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='side_affinity',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='sleep_posture',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='social_disposition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='suppression_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='temperament',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='thermal_state',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='thirst_pattern',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='vaccination_effects',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='vaccination_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='weeping_tendency',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
