# Generated by Django 6.0.6 on 2026-07-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_medicalhistory_aggravation_factors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsettings',
            name='google_map_link',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
