# Generated by Django 6.0.6 on 2026-07-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_alter_doctorsettings_google_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsettings',
            name='google_map_link',
            field=models.TextField(blank=True),
        ),
    ]
