# Generated by Django 6.0.7 on 2026-08-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_alter_doctorsettings_google_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsettings',
            name='appointment_duration',
            field=models.PositiveIntegerField(default=15, help_text='Approximate appointment duration in minutes.'),
        ),
    ]
